name: {{name.snakeCase()}}
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_core:
    git:
      url: https://github.com/yzzzd/fluttercore.git
      ref: 2.0.2
  
  cupertino_icons: ^1.0.2
  floor: ^1.4.2
  sqflite: ^2.3.0
  flutter_dotenv: ^5.1.0
  flutter_native_splash: ^2.3.3
  awesome_dio_interceptor: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^8.1.0
  floor_generator: ^1.4.2
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
  flutter_gen_runner:
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/images/
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: assets/fonts/Roboto-Regular.ttf
  #       - asset: assets/fonts/Roboto-Bold.ttf
  #         weight: 700
